import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "../styles/globals.css";
import { helvetica } from "@/assets/fonts/helvetica/helvetica";
import Providers from "@/components/providers/providers";
import ClientOnly from "@/components/client-only";
import dynamic from "next/dynamic";
import { DeliveryProvider } from "@/context/checkout/delivery-context";
import { getUserActiveAdress } from "@/actions/address/user-address.actions";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const ReduxProvider = dynamic(() => import("@/store/redux-provider"), {
//   ssr: false,
// });

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const deliveryAddress = await getUserActiveAdress();
  return (
    <html lang="en">
      <body className={`${helvetica.className} max-w-[1924px]`}>
        <Providers>
          <ClientOnly>
            {/* <DeliveryProvider deliveryAddress={deliveryAddress}> */}
            {children}
            {/* </DeliveryProvider> */}
          </ClientOnly>
        </Providers>
      </body>
    </html>
  );
}
