import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "../styles/globals.css";
import { helvetica } from "@/assets/fonts/helvetica/helvetica";
import ClientOnly from "@/components/ui/client-only";
import AppProviders from "@/components/providers/app-providers";
import Navbar from "@/components/common/navbar/Navbar";
import Footer from "@/components/common/footer/footer";
import { footerLinks, footerMenu } from "@/assets/data/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${helvetica.className} max-w-[1924px]`}>
        <ClientOnly>
          <AppProviders>
            <Navbar />
            {children}
            <Footer footerLinks={footerLinks} />
          </AppProviders>
        </ClientOnly>
      </body>
    </html>
  );
}
